<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DBConnectionTester</RootNamespace>
    <AssemblyName>DBConnectionTester</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.7" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.31" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Npgsql" Version="8.0.9" />
    <PackageReference Include="System.Data.Odbc" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Remove="tests\**\*" />
    <None Remove="tests\**\*" />
  </ItemGroup>
</Project>
